-- Zaker: grade/subject availability control
-- Deployed to Supabase project llhmkyighydokneqwrdj on 2026-09-24.

create table if not exists public.content_availability (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('grade','subject')),
  grade text not null check (grade in ('p4','p5','p6','prep1','prep2','prep3')),
  track text not null default 'shared' check (track in ('shared','languages','arabic')),
  subject_code text not null default '',
  status text not null default 'building' check (status in ('active','building','review','disabled')),
  message text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null,
  constraint content_availability_shape_chk check (
    (scope='grade' and track='shared' and subject_code='')
    or
    (scope='subject' and track in ('languages','arabic') and subject_code<>'')
  ),
  constraint content_availability_unique unique(scope,grade,track,subject_code)
);

alter table public.content_availability enable row level security;
grant select on public.content_availability to anon, authenticated;
revoke insert, update, delete on public.content_availability from anon, authenticated;

drop policy if exists "content availability public read" on public.content_availability;
create policy "content availability public read"
on public.content_availability
for select to anon, authenticated
using (true);

create or replace function public.get_content_availability(p_grade text, p_track text default 'languages')
returns jsonb
language sql stable security invoker
set search_path = public
as $$
  select coalesce(
    jsonb_agg(jsonb_build_object(
      'scope',c.scope,'grade',c.grade,'track',c.track,'subject_code',c.subject_code,
      'status',c.status,'message',c.message,'updated_at',c.updated_at
    ) order by case when c.scope='grade' then 0 else 1 end,c.subject_code),
    '[]'::jsonb
  )
  from public.content_availability c
  where c.grade=p_grade and (c.track='shared' or c.track=p_track);
$$;

revoke all on function public.get_content_availability(text,text) from public;
grant execute on function public.get_content_availability(text,text) to anon,authenticated;

create or replace function public.admin_set_content_availability(
  p_scope text,p_grade text,p_track text,p_subject_code text,p_status text,p_message text default ''
) returns jsonb
language plpgsql security definer
set search_path=public
as $$
declare v_track text; v_subject text; v_old jsonb; v_new jsonb;
begin
  if not (
    public.is_super_admin()
    or exists(
      select 1 from public.admin_roles r
      where r.user_id=auth.uid() and r.active and r.role_code='content_manager'
    )
  ) then raise exception 'Content Manager access required'; end if;

  if p_scope not in ('grade','subject') then raise exception 'invalid scope'; end if;
  if p_grade not in ('p4','p5','p6','prep1','prep2','prep3') then raise exception 'invalid grade'; end if;
  if p_status not in ('active','building','review','disabled') then raise exception 'invalid status'; end if;

  if p_scope='grade' then v_track:='shared'; v_subject:='';
  else
    if p_track not in ('languages','arabic') then raise exception 'invalid track'; end if;
    v_track:=p_track; v_subject:=lower(trim(coalesce(p_subject_code,'')));
    if v_subject='' then raise exception 'subject code required'; end if;
  end if;

  select to_jsonb(c) into v_old from public.content_availability c
  where c.scope=p_scope and c.grade=p_grade and c.track=v_track and c.subject_code=v_subject;

  insert into public.content_availability(scope,grade,track,subject_code,status,message,updated_at,updated_by)
  values(p_scope,p_grade,v_track,v_subject,p_status,coalesce(p_message,''),now(),auth.uid())
  on conflict(scope,grade,track,subject_code)
  do update set status=excluded.status,message=excluded.message,updated_at=now(),updated_by=auth.uid();

  select to_jsonb(c)-'updated_by' into v_new from public.content_availability c
  where c.scope=p_scope and c.grade=p_grade and c.track=v_track and c.subject_code=v_subject;

  perform public.admin_log(
    'set_content_availability','content_availability',
    p_scope||':'||p_grade||':'||v_track||':'||v_subject,v_old,v_new
  );
  return v_new;
end;
$$;

revoke all on function public.admin_set_content_availability(text,text,text,text,text,text) from public,anon;
grant execute on function public.admin_set_content_availability(text,text,text,text,text,text) to authenticated;
